changelog:
  exclude:
    labels:
      - "Release: Ignore for Changelog"
  categories:
    - title: Breaking Changes 🛠
      labels:
        - "Type: Breaking Change"
    - title: New Features 🎉
      labels:
        - "Type: Epic"
        - "Type: Story"
        - "Type: Enhancement"
    - title: Fixes
      labels:
        - "Type: Bug"
    - title: Docs
      labels:
        - "Area: Docs"
    - title: Demo notebooks
      labels:
        - "Area: Demo"
    - title: Under the hood
      labels:
        - "Type: Under the Hood"
    - title: Other Changes
      labels:
        - "*"
