name: "Tracker tests"

on:
  push:
    paths:
      - 'schema/**'
      - 'tracker/**'
      # Also run if we update this file, or any other workflow
      - '.github/**'

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        working-directory: tracker
        run: yarn install

  run-check-dependencies:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        working-directory: tracker
        run: yarn install

      - name: Check dependencies
        working-directory: tracker
        run: yarn check:dependencies

  run-ts-check:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        working-directory: tracker
        run: yarn install

      - name: Run TypeScript check
        working-directory: tracker
        run: yarn tsc

  run-unit-tests:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        working-directory: tracker
        run: yarn install

      - name: Run unit tests
        working-directory: tracker
        run: yarn test:ci

  run-ts-schema-check:
    runs-on: ubuntu-latest
    needs: [install-dependencies]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        working-directory: tracker
        run: yarn install

      - name: Test if TS schema is up to date
        working-directory: tracker
        run: |
          yarn utils:generate
          test $(git status -s -uno | wc -l) -eq 0
